version: '2'
services:
    saas-app:
        image: saas
        external_links:
            - saas-mysql:mysql
            - saas-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/saas?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    saas-mysql:
        extends:
            file: mysql.yml
            service: saas-mysql
    saas-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: saas-elasticsearch
